#!/bin/bash
# ==============================================================================
# BASTI'S BASH DEFAULT SETTINGS
# Commonly used bash settings on various machines. 
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# ==============================================================================

# Locale settings  
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# Don't use ^D to exit
set -o ignoreeof

# Make bash append rather than overwrite the history on disk
shopt -s histappend

# Don't put duplicate lines in the history.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups

# Alias settings 
alias less='less -r'                          # raw control characters
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
alias ls='ls -hF --color=tty'                 # classify files in colour
alias ll='ls -l'                              # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #
alias ..="cd .."
alias ...="cd ../../"

# ==============================================================================
echo "Loading basti's bash defaults done." 