#!/bin/bash
# ==============================================================================
# NOBODY CARES
# A cronjobbable script to remove tweets older that x days.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# ==============================================================================

HANDLE=
DELETE=
MAX_AGE_DAYS=3

function show_help () {
	[ ! -z "$1" ] && echo "$1"
cat << EOF

Usage: $( basename $0 ) -t [HANDLE] -m [MAXD] -f
  -t [HANDLE]    Twitter handle, e.g., @myhandle
  -m [MAXD]      Maximum days to preserve (default: $MAX_AGE_DAYS)
  -f             Actually delete tweets, don't just list the candidates.

EOF
	exit 1
}

while getopts "t:m:f" opt; do
    case "$opt" in
    t) HANDLE="$OPTARG";;
	m) MAX_AGE_DAYS=$OPTARG;;
    f) DELETE=1;;
	*) show_help "Illegal argument.";;
	esac
done

[ -z $( command -v t ) ] && {
    echo "'t' gem (https://github.com/sferik/t) not installed."
    exit 1
}
[ -z "$HANDLE" ] && show_help "No twitter handle provided."
[[ ! $MAX_AGE_DAYS =~ ^[0-9]+$ ]] && show_help "Age must be a number. D'uh!"
[ ! $MAX_AGE_DAYS -ge 1 ] && show_help "Invalid maximum age. Must be >= 1."

now=$( date +%s )
oldest=$(( $now - ( $MAX_AGE_DAYS * 24 * 60 * 60 ) ))
# echo "-- oldest allowed: $oldest"

t timeline $HANDLE --csv --number 10000 | while read tweet; do
	[ ! -z "$( echo $tweet | grep "#bastisite" )" ] && continue
	[ ! -z "$( echo $tweet | grep "follow at own risk ")" ] && continue
	[ ! -z "$( echo $tweet | grep -e "^ID" )" ] && continue
	datetime=$( awk -F',' '{ print $2"\n" }' <<< $tweet )
	datetime=$( date -d "$datetime" +%s )
	[ $datetime -le $oldest ] && {
		echo "--- $tweet"
		id=$( sed -e "s/,.*//" <<< $tweet )
        [ "$DELETE" == 1 ] && t delete status -f $id
	}
done
