#!/bin/bash
# ==============================================================================
# MOUSE-PASTE-TEXT (BASTI's BASH COMMONS)
# Pastes the provided text snippet out via the mouse-clipboard. Useful to
# bind shortcuts to generate text snippets.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# ==============================================================================

[ -z $( command -v xclip ) ] && { echo "xclip missing."; exit 1; }
[ -z $( command -v xdotool ) ] && { echo "xdotool missing."; exit 1; }
[ -z "$1" ] && { echo "no phrase provided."; exit 1; }
echo "$1" | xclip && sleep 0.05 && xdotool mousedown 2 mouseup 2
