#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const express = require('express');
const server = express();
const bs = require('browser-sync').create();
const internalPort = 61426;

const setNoCache = function(request, response, next) {
    response.header('Cache-Control',
        'private, no-cache, no-store, must-revalidate');
    response.header('Expires', '-1');
    response.header('Pragma', 'no-cache');
    next();
};

const watchFolder = path.resolve('.')
console.log('Watching files in ' + watchFolder);

server.use(setNoCache);
server.use('/', express.static(watchFolder));
server.listen(internalPort);

bs.watch(watchFolder + '/**/*.js').on('change', bs.reload);
bs.watch(watchFolder + '/**/*.html').on('change', bs.reload);
bs.watch(watchFolder + '/**/*.css').on('change', bs.reload);
bs.init({
    proxy: 'http://localhost:' + internalPort,
    port: 1337,
    ui: false,
    notify: false,
    logLevel: 'info',
});

console.log('>> http://localhost:1337');
