#!/bin/bash
# ==============================================================================
# GIT ALL (BASTI's BASH COMMONS)
# A simple wrapper to invoke a git command on any git repository in a 
# child folder (non-recursive). 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# ==============================================================================

[ $# == 0 ] && { echo "No git argument provided."; exit 1; }
gitcmd=$1

gitsummary () {
    absdir=$( readlink -f $1 )
    tmpf=$( mktemp )
    dirn=$( basename $( dirname $absdir ) )
    printf "=%.0s" $( seq 1 ${#dirn} ) >> $tmpf
    echo -e "\n${dirn}" >> $tmpf
    printf "=%.0s" $( seq 1 ${#dirn} ) >> $tmpf
    echo -e "\n" >> $tmpf
    currdir=$( pwd )
    cd $absdir
    cd ..
    git $2 2>&1 >> $tmpf
    echo "" >> $tmpf
    cd $currdir
    echo "$tmpf"
}
export -f gitsummary
    
tmpfiles=$( mktemp )
{
for dir in $( find -maxdepth 2 -type d -name ".git" ); do \
echo "$dir"; done | xargs -P10 -I {} bash -c 'gitsummary $1 $2' _ {} $gitcmd
} > $tmpfiles 

clear
while read tmpfile; do cat $tmpfile; rm $tmpfile; done < $tmpfiles
rm $tmpfiles 
