#!/bin/bash
# ==============================================================================
# DELETE OLD TWEETS
# A cronjobbable script to remove tweets older that x days and matching pattern.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# ==============================================================================

DELETE=
MAX_AGE_DAYS=3

function show_help () {
	[ ! -z "$1" ] && echo "$1"
cat << EOF

Usage: $( basename $0 ) -t [HANDLE] -m [MAXD] -f -e [IPATT_1] .. -e [IPATT_n]
  -t [HANDLE]    Twitter handle, e.g., @myhandle.
  -m [MAXD]      Maximum days to preserve (default: $MAX_AGE_DAYS).
  -f             Actually delete tweets, don\'t just list the candidates.
  -e [IPATT]     Removes tweets from results containing the given expressions.
  -l [FILE]      Optional target logfile.

Example: $( basename $0 ) -t @my_handle -m 3 -e "#Yolo" -e "@another_handle" -l /var/log/my.log

EOF
	exit 1
}

function log() {
	[ ! -z $LOG_FILE ] && echo $@ >> $LOG_FILE
	echo $@
}


while getopts "t:m:e:fl:" opt; do
    case "$opt" in
    t) HANDLE="$OPTARG";;
	m) MAX_AGE_DAYS=$OPTARG;;
	e) IPATT+=("$OPTARG");;
    f) DELETE=1;;
	l) LOG_FILE="$OPTARG";;
	*) show_help "Illegal argument.";;
	esac
done

[ -z $( command -v t ) ] && {
    >&2 echo "'t' gem (https://github.com/sferik/t) not installed."
    exit 1
}
TCOM=$( which t )
[ -z "$HANDLE" ] && show_help "No twitter handle provided."
[[ ! $MAX_AGE_DAYS =~ ^[0-9]+$ ]] && show_help "Age must be a number. D'uh!"
[ ! $MAX_AGE_DAYS -ge 1 ] && show_help "Invalid maximum age. Must be >= 1."

now=$( date +%s )
oldest=$(( $now - ( $MAX_AGE_DAYS * 24 * 60 * 60 ) ))

#log "--- $( date ) - $TCOM - delete=$DELETE"
$TCOM timeline $HANDLE --csv --number 10000 | while read tweet; do
	[ ! -z "$( echo $tweet | grep -e "^ID" )" ] && continue # remove header
	ipatt_matched=0
	for ipatt in "${IPATT[@]}"; do
	    [ ! -z "$( echo $tweet | grep -e "$ipatt" )" ] && ipatt_matched=1
	done
	[ $ipatt_matched == 1 ] && continue
	datetime=$( awk -F',' '{ print $2"\n" }' <<< $tweet )
	datetime=$( date -d "$datetime" +%s )
	[ $datetime -le $oldest ] && {
		log "+ $tweet"
		id=$( sed -e "s/,.*//" <<< $tweet )
        [ "$DELETE" == 1 ] && $TCOM delete status -f $id
	}
done

