#!/bin/bash
# ==============================================================================
# GIT ALL (BASTI's BASH COMMONS)
# A simple wrapper to invoke a git command on any git repository in a 
# child folder (non-recursive). 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# ==============================================================================

[ $# == 0 ] && { echo "No git argument provided."; exit 1; }

git-summary () {
    tmpf=$( mktemp )
    dirn=$( basename $( dirname $1 ) )
    printf "=%.0s" $( seq 1 ${#dirn} ) >> $tmpf
    echo -e "\n${dirn}" >> $tmpf
    printf "=%.0s" $( seq 1 ${#dirn} ) >> $tmpf
    echo "" >> $tmpf
    currdir=$( pwd )
    cd $1
    cd ..
    git $2 2>&1 >> $tmpf
    echo "" >> $tmpf
    cat $tmpf 
    rm $tmpf 
    cd $currdir
}

for dir in $( find -maxdepth 2 -type d -name ".git" )
do
    git-summary $( readlink -f $dir ) $1 
done
