#!/bin/bash
# ==============================================================================
# TIMEOUT [-SIG] time [--] command args...
# Run the given command until completion, but kill it if it runs too long.
# Specifically designed to exit immediatally (no sleep interval) and clean up
# nicely without messages or leaving any extra processes when finished.
#
# Example use
#    timeout 5 countdown
#
# Taken from https://www.ict.griffith.edu.au/anthony/software/timeout.sh
# ==============================================================================

PROGNAME=`type $0 | awk '{print $3}'`  # search for executable on path
PROGDIR=`dirname $PROGNAME`            # extract directory of program
PROGNAME=`basename $PROGNAME`          # base name of program
Usage() {                              # output the script comments as docs
  echo >&2 "$PROGNAME:" "$@"
    sed >&2 -n '/^###/q; /^#/!q; s/^#//; s/^ //; 3s/^/Usage: /; 2,$ p' \
            "$PROGDIR/$PROGNAME"
  exit 10;
}

SIG=-TERM

while [  $# -gt 0 ]; do
  case "$1" in
  --)     shift; break ;;    # forced end of user options
  -\?|--help|--doc*) Usage ;;
  [0-9]*) TIMEOUT="$1" ;;
  -*)     SIG="$1" ;;
  *)      break ;;           # unforced  end of user options
  esac
shift   # next option
done

# run subroutine in backgrouds and get its pid
"$@" &
command_pid=$!

# timeout sub-process abort countdown after ABORT seconds! also backgrounded
sleep_pid=0
( trap 'kill -TERM $sleep_pid; exit 1' 1 2 3 15  # cleanup sleep process
  sleep $TIMEOUT &             # sleep timeout period
  sleep_pid=$!
  wait $sleep_pid
  kill $SIG $command_pid 2>/dev/null   # Abort the command
  exit 1
) &
timeout_pid=$!

# Wait for main command to finished or be timed out
wait $command_pid
status=$?

# Clean up timeout sub-shell - if it is still running!
kill $timeout_pid 2>/dev/null
wait $timeout_pid 2>/dev/null

# Uncomment to check if a LONG sleep still running (no sleep should be)
# sleep 1
# echo "-----------"
# /bin/ps j  # uncomment to show if abort "sleep" is still sleeping

exit $status
