#!/bin/bash
# Run this by executing:
# bash <(wget -qO- https://raw.githubusercontent.com/BastiTee/bastis-bash-commons/master/bootstrap)

# basic ubuntu setup
sudo apt update && \
sudo apt upgrade -y && \
sudo apt install -y git vim docker.io gcc make htop curl && \

# ssh keys 
[ ! -f ~/.ssh/id_rsa.pub ] && {
  ssh-keygen
  cat ~/.ssh/id_rsa.pub
}

# get working environment
cd ~
home=$( readlink -f $( pwd ) )
mkdir git
cd git
git_root=$( readlink -f $( pwd ) )
for project in bastis-bash-commons dockerfiles ubersettings
do
  curl -sL -o ${project}.zip https://github.com/BastiTee/${project}/archive/master.zip
  unzip ${project}.zip 
  mv ${project}-master ${project}
done

# link working environment
cd ~/git/ubersettings/shell-rcs
./link.sh
cat << EOF > ~/.bashrc
source ${git_root}/bastis-bash-commons/bbc-bash-defaults
export PATH=${PATH}:${git_root}/bastis-bash-commons:${git_root}/dockerfiles
EOF

# run some setups 
sudo usermod -aG docker $(whoami)
sudo systemctl restart docker.service

# finish 
cd $home
